name:                github-t
version:             0.1.0.0
github:              "eamsden/github-t"
license:             BSD3
author:              "Edward Amsden"
maintainer:          "edwardamsden@gmail.com"
copyright:           "2018 Edward Amsden"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/github-t#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- bytestring-lexing
- exceptions
- github
- http-types
- http-client
- http-client-tls
- mtl
- network-uri
- text
- time
- vector

library:
  source-dirs: src

tests:
  github-t-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - github-t
